### ISSUE TITLE
data distribution analysis

### ISSUE THREAD

**Issue by ahuazuipiaoliang** [pixmoving-moveit/learning_based_vehicle_calibration#7]
@CristianGariboldi Is it possible to analyze the data distribution of data collection?

**Comment by CristianGariboldi** [comment]
@ahuazuipiaoliang  Now, when you launch the neural network script for training and visualization, it will also plot the data distribution as you can see in the picture below:

![dioss](https://github.com/pixmoving-moveit/learning_based_vehicle_calibration/assets/143978678/41c65ca1-fb36-4b77-a1f0-e5ec4660f15b)

**Comment by CristianGariboldi** [comment]
@ahuazuipiaoliang Now, when you launch the neural network script for training and visualization, it will also plot the data distribution as you can see in the picture below:

![dioss](https://github.com/pixmoving-moveit/learning_based_vehicle_calibration/assets/143978678/f9bd09db-5c51-4f66-9494-7d7cfbaff815)

Please test the branch, so that we can set it as the default one.
I will close this issue so far, feel free to open it again in case of problems.
